# Generated by Django 5.2.1 on 2025-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('c', 'C')], max_length=10),
        ),
    ]
